# Generated by Django 5.0.6 on 2024-06-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_role_type'),
        ('assessments', '0003_answer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='role',
        ),
        migrations.AddField(
            model_name='question',
            name='role_type',
            field=models.IntegerField(choices=[(1, 'Sênior'), (2, 'Assistente')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
