# Generated by Django 5.1 on 2024-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_question_weight_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationschedule',
            name='commitment',
            field=models.CharField(choices=[('Auditoria externa - Preliminar', 'Auditoria externa - Preliminar'), ('Auditoria externa - Controle Interno', 'Auditoria externa - Controle Interno'), ('Auditoria externa - Final', 'Auditoria externa - Final'), ('Inventário', 'Inventário'), ('Serviços Financeiros', 'Serviços Financeiros'), ('Auditoria Interna', 'Auditoria Interna'), ('Incorporação', 'Incorporação'), ('Auditoria Cooperativa', 'Auditoria Cooperativa'), ('Demonstrações Financeiras - Final', 'Demonstrações Financeiras - Final'), ('Demonstrações Financeiras - Preliminar', 'Demonstrações Financeiras - Preliminar'), ('Auditoria contínua', 'Auditoria contínua'), ('Revisão contábil', 'Revisão contábil'), ('Outros', 'Outros')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationschedule',
            name='other_commitment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
