# Generated by Django 5.1 on 2024-09-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_evaluationschedule_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationschedule',
            name='work',
        ),
    ]
