# Generated by Django 5.1 on 2024-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_evaluationschedule_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='commitment',
            field=models.CharField(blank=True, choices=[('Auditoria externa - Preliminar', 'Auditoria externa - Preliminar'), ('Auditoria externa - Controle Interno', 'Auditoria externa - Controle Interno'), ('Auditoria externa - Final', 'Auditoria externa - Final'), ('Inventário', 'Inventário'), ('Serviços Financeiros', 'Serviços Financeiros'), ('Auditoria Interna', 'Auditoria Interna'), ('Incorporação', 'Incorporação'), ('Auditoria Cooperativa', 'Auditoria Cooperativa'), ('Demonstrações Financeiras - Final', 'Demonstrações Financeiras - Final'), ('Demonstrações Financeiras - Preliminar', 'Demonstrações Financeiras - Preliminar'), ('Auditoria contínua', 'Auditoria contínua'), ('Revisão contábil', 'Revisão contábil'), ('Outros', 'Outros')], max_length=50, null=True, verbose_name='Compromisso'),
        ),
        migrations.AddField(
            model_name='work',
            name='other_commitment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro Compromisso'),
        ),
    ]
