# Generated by Django 5.1 on 2024-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_work_commitment_work_other_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Trabalho'),
        ),
    ]
