name: Build and deploy Python app to Azure Web App - admooreprisma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Create and activate a virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
<<<<<<< HEAD
=======

      - name: Run collectstatic
<<<<<<< HEAD
        run: python manage.py collectstatic
>>>>>>> 7a46666 (Update main_admooreprisma.yml)
=======
        run: python manage.py collectstatic --noinput
>>>>>>> f82878b (Update main_admooreprisma.yml)
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . --exclude './venv/*'

      # Upload the zipped artifact
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the zipped artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure Web App using the publish profile
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'admooreprisma'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2AC1F2254E0140BB9F0AAC86B8D58E9D }}
